---
services:
  perceived-temp-service:
    container_name: svc-open-window
    image: svenschmidt1502/svc-open-window:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
    deploy:
      replicas: 1