---
services:
  perceived-temp-service:
    container_name: open_window
    image: svenschmidt1502/open_window:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
    deploy:
      replicas: 1