---
services:
  perceived-temp-service:
    container_name: svc-open-window
    image: svenschmidt1502/svc-open-window:latest
    environment:
      - 'KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}' 
      - 'KAFKA_GROUP_ID=${KAFKA_GROUP_ID}' 
      - 'KAFKA_INDOOR_TOPIC=${KAFKA_INDOOR_TOPIC}'
      - 'KAFKA_OUTDOOR_TOPIC=${KAFKA_OUTDOOR_TOPIC}'
    deploy:
      replicas: 1